spring:
    datasource:
        url: jdbc:mysql://47.104.220.61:3306/hj?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: hj
        password: hjadmin
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    
    
